spring:
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/gaaji-chat
      authentication-database: admin
      database: gaaji-chat
      username: root
      password: 1234
      test:
        connectionString: mongodb://127.0.0.1:27017/gaaji-chat
